title:             Vanessa Olivia
email:             jujubejag@yahoo.com
description:       Music
author:            Julie
#url:               "localhost:4000"
url:               "http://vanessaoliviamusic.github.io/"
baseurl:

# Social Profiles
#twitter_username:  twitter
#github_username:   vanessaoliviamusic
#facebook_username: facebook

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  
  
background-color:             '#f8f8f8'
